// Game and Player State
let state = {
    lang: "en",
    class: null,
    name: "Hero",
    hp: 0,
    maxHp: 0,
    str: 10,
    dex: 10,
    int: 10,
    ac: 10,
    weaponName: "Fists",
    weaponDamage: 4,
    skills: [],
    xp: 0,
    level: 1,
    gold: 15,
    inventory: [],
    currentRoom: "graveyard",
    previousRoom: "graveyard",
    combat: null,
    npcDialogueIndices: {},
    companion: null, // "Cassyt"
    gogglesEquipped: false,
    readObeliskRunes: false,
    blueLeverPulled: false,
    greenLeverPulled: false,
    allyKnight: false,
    sunfireOilEquipped: false,
    holdingBreath: false,
    allyDragon: false,
    tyrOfferingDone: false,
    mirrorShattered: false,
    readTomeActive: false,
    yovirQuestOffered: false,
    yovirQuestAccepted: false,
    welcomersQuestOffered: false,
    welcomersQuestAccepted: false,
    arvaxQuestOffered: false,
    antitoxinDuration: 0,
    cassytOfferActive: false
};
